# Generated by Django 4.0.2 on 2022-03-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_user_department_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('DEF', 'СТАНДАРТ'), ('ERR', 'ОШИБКА'), ('SUC', 'УСПЕХ'), ('WAI', 'ОЖИДАНИЕ')], default='DEF', max_length=3)),
                ('title', models.CharField(default=None, max_length=100, null=True)),
                ('button_name', models.CharField(default=None, max_length=255, null=True)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='regulations.stage')),
                ('performer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Regulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reg_author', to='user.user')),
                ('first_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regulations.stage')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reg_performer', to='user.user')),
            ],
        ),
    ]
