# Generated by Django 4.0.2 on 2022-03-06 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_department'),
        ('regulations', '0003_regulations_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulations',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_author', to='user.user'),
        ),
        migrations.AlterField(
            model_name='regulations',
            name='first_stage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='regulations.stage'),
        ),
        migrations.AlterField(
            model_name='regulations',
            name='performer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_performer', to='user.user'),
        ),
    ]
