# Generated by Django 4.0.2 on 2022-02-23 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0004_remove_violation_subspecies'),
        ('vsubspecies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsubspecies',
            name='violation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='violation.violation'),
        ),
    ]
