# Generated by Django 4.0.2 on 2022-02-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='organization',
        ),
        migrations.AddField(
            model_name='department',
            name='organizations',
            field=models.ManyToManyField(to='organization.Organization'),
        ),
    ]
