# Generated by Django 4.0.2 on 2022-02-27 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='department.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
