# Generated by Django 4.0.2 on 2022-02-23 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsubspecies', '0001_initial'),
        ('violation', '0002_alter_violation_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='subtype',
        ),
        migrations.AddField(
            model_name='violation',
            name='subspecies',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='vsubspecies.vsubspecies'),
        ),
    ]
