# Generated by Django 4.0.2 on 2022-02-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0003_remove_violation_subtype_violation_subspecies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='subspecies',
        ),
    ]
