# Generated by Django 4.0.2 on 2022-02-23 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('status', '0001_initial'),
        ('district', '0001_initial'),
        ('violation', '0001_initial'),
        ('employees', '0002_alter_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('number', models.IntegerField()),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='district.district')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='organization.organization')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='violation.violation')),
            ],
        ),
    ]
