# Generated by Django 4.0.2 on 2022-02-27 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('company', '0001_initial'),
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('Дзержинский', 'Дзержинский'), ('Кировский', 'Кировский')], max_length=100)),
                ('date', models.DateTimeField()),
                ('number', models.CharField(max_length=6)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regulations.regulations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user')),
            ],
        ),
    ]
