# Generated by Django 4.0.2 on 2022-03-06 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('user', '0002_alter_user_department_alter_user_email_and_more'),
        ('regulations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('STR', 'СТРОКА'), ('INT', 'ЦЕЛОЕ ЧИСЛО'), ('FLT', 'ДРОБНОЕ ЧИСЛО'), ('DAT', 'ДАТА'), ('FIL', 'ФАЙЛ'), ('LIS', 'СПИСОК'), ('USR', 'СОТРУДНИК'), ('CMP', 'ОРГАНИЗАЦИЯ'), ('DIS', 'РАЙОН'), ('NUM', 'НОМЕР')], max_length=3)),
                ('title', models.CharField(max_length=255)),
                ('show_in_table', models.BooleanField(default=False)),
                ('regulations', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='regulations.regulations')),
            ],
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_string', models.CharField(default=None, max_length=255, null=True)),
                ('value_int', models.IntegerField(default=None, null=True)),
                ('value_float', models.FloatField(default=None, null=True)),
                ('value_date', models.DateTimeField(default=None, null=True)),
                ('value_file', models.FileField(default=None, null=True, upload_to='')),
                ('value_list', models.CharField(default=None, max_length=100, null=True)),
                ('value_district', models.CharField(choices=[('DZE', 'Дзержинский'), ('KIR', 'Кировский')], default=None, max_length=3, null=True)),
                ('is_choosed', models.BooleanField(default=None, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.fields')),
                ('value_company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('value_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_author', to='user.user')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_performer', to='user.user')),
                ('regulations', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regulations.regulations')),
            ],
        ),
    ]
