# Generated by Django 4.0.2 on 2022-03-06 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0002_alter_regulations_author_and_more'),
        ('user', '0003_alter_user_department'),
        ('company', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='regulations',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='regulations.regulations'),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_author', to='user.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_performer', to='user.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='regulations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='regulations.regulations'),
        ),
        migrations.AlterField(
            model_name='values',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task.fields'),
        ),
        migrations.AlterField(
            model_name='values',
            name='value_company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.company'),
        ),
        migrations.AlterField(
            model_name='values',
            name='value_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.user'),
        ),
    ]
