# Generated by Django 4.0.2 on 2022-03-01 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_department_alter_user_email_and_more'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('STR', 'СТРОКА'), ('NUM', 'ЧИСЛО'), ('DAT', 'ДАТА'), ('MON', 'ВАЛЮТА'), ('FIL', 'ФАЙЛ'), ('LIS', 'СПИСОК')], max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewRegulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_type', models.CharField(max_length=255)),
                ('button_name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='task.newregulations')),
                ('performer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='NewValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.newfields')),
            ],
        ),
        migrations.CreateModel(
            name='NewTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='user.user')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performer', to='user.user')),
                ('regulations', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.newregulations')),
            ],
        ),
        migrations.AddField(
            model_name='newfields',
            name='regulations',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='task.newregulations'),
        ),
    ]
