# Generated by Django 4.0.2 on 2022-03-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0004_alter_regulations_author_and_more'),
        ('task', '0002_alter_fields_regulations_alter_task_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fields',
            name='regulations',
        ),
        migrations.AddField(
            model_name='fields',
            name='stage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='regulations.stage'),
        ),
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='regulations.stage'),
            preserve_default=False,
        ),
    ]
