# Generated by Django 4.0.2 on 2022-03-04 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('user', '0002_alter_user_department_alter_user_email_and_more'),
        ('task', '0002_newfields_newregulations_newvalues_newtask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newvalues',
            name='value',
        ),
        migrations.AddField(
            model_name='newvalues',
            name='is_choosed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='newvalues',
            name='value_company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
        migrations.AddField(
            model_name='newvalues',
            name='value_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='newvalues',
            name='value_file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='newvalues',
            name='value_float',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='newvalues',
            name='value_int',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='newvalues',
            name='value_list',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newvalues',
            name='value_string',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newvalues',
            name='value_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.user'),
        ),
        migrations.AlterField(
            model_name='newfields',
            name='field_type',
            field=models.CharField(choices=[('STR', 'СТРОКА'), ('INT', 'ЦЕЛОЕ ЧИСЛО'), ('FLT', 'ДРОБНОЕ ЧИСЛО'), ('DAT', 'ДАТА'), ('FIL', 'ФАЙЛ'), ('LIS', 'СПИСОК'), ('USR', 'СОТРУДНИК'), ('CMP', 'ОРГАНИЗАЦИЯ')], max_length=255),
        ),
    ]
