# Generated by Django 4.0.2 on 2022-03-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_newvalues_value_newvalues_is_choosed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newregulations',
            name='title',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newfields',
            name='field_type',
            field=models.CharField(choices=[('STR', 'СТРОКА'), ('INT', 'ЦЕЛОЕ ЧИСЛО'), ('FLT', 'ДРОБНОЕ ЧИСЛО'), ('DAT', 'ДАТА'), ('FIL', 'ФАЙЛ'), ('LIS', 'СПИСОК'), ('USR', 'СОТРУДНИК'), ('CMP', 'ОРГАНИЗАЦИЯ')], max_length=3),
        ),
        migrations.AlterField(
            model_name='newregulations',
            name='reg_type',
            field=models.CharField(choices=[('DEF', 'СТАНДАРТ'), ('ERR', 'ОШИБКА'), ('SUC', 'УСПЕХ'), ('WAI', 'ОЖИДАНИЕ')], default='DEF', max_length=3),
        ),
    ]
