# Generated by Django 4.0.2 on 2022-03-06 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0004_alter_regulations_author_and_more'),
        ('task', '0003_remove_fields_regulations_fields_stage_task_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='regulations.stage'),
        ),
    ]
