# Generated by Django 4.0.2 on 2022-03-06 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task.task'),
        ),
    ]
