# Generated by Django 4.0.2 on 2022-03-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_newregulations_title_alter_newfields_field_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfields',
            name='show_in_table',
            field=models.BooleanField(default=False),
        ),
    ]
