# Generated by Django 4.0.2 on 2022-03-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_newfields_show_in_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='newvalues',
            name='value_district',
            field=models.CharField(choices=[('DZE', 'Дзержинский'), ('KIR', 'Кировский')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='newfields',
            name='field_type',
            field=models.CharField(choices=[('STR', 'СТРОКА'), ('INT', 'ЦЕЛОЕ ЧИСЛО'), ('FLT', 'ДРОБНОЕ ЧИСЛО'), ('DAT', 'ДАТА'), ('FIL', 'ФАЙЛ'), ('LIS', 'СПИСОК'), ('USR', 'СОТРУДНИК'), ('CMP', 'ОРГАНИЗАЦИЯ'), ('DIS', 'РАЙОН')], max_length=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='district',
            field=models.CharField(choices=[('DZE', 'Дзержинский'), ('KIR', 'Кировский')], max_length=100),
        ),
    ]
