# Generated by Django 4.0.2 on 2022-03-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0004_alter_regulations_author_and_more'),
        ('task', '0005_values_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('action', models.CharField(max_length=65535)),
                ('stage', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='regulations.stage')),
                ('task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task.task')),
            ],
        ),
    ]
