# Generated by Django 4.0.2 on 2022-03-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_newvalues_value_district_alter_newfields_field_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newfields',
            name='field_type',
            field=models.CharField(choices=[('STR', 'СТРОКА'), ('INT', 'ЦЕЛОЕ ЧИСЛО'), ('FLT', 'ДРОБНОЕ ЧИСЛО'), ('DAT', 'ДАТА'), ('FIL', 'ФАЙЛ'), ('LIS', 'СПИСОК'), ('USR', 'СОТРУДНИК'), ('CMP', 'ОРГАНИЗАЦИЯ'), ('DIS', 'РАЙОН'), ('NUM', 'НОМЕР')], max_length=3),
        ),
    ]
