# Generated by Django 4.0.2 on 2022-03-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_newtask_is_completed_alter_newfields_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newregulations',
            name='button_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
