# Generated by Django 4.0.3 on 2022-03-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_history_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='field_type',
            field=models.CharField(choices=[('STR', 'СТРОКА'), ('INT', 'ЦЕЛОЕ ЧИСЛО'), ('FLT', 'ДРОБНОЕ ЧИСЛО'), ('DAT', 'ДАТА'), ('FIL', 'ФАЙЛ'), ('LIS', 'СПИСОК'), ('USR', 'СОТРУДНИК'), ('CMP', 'ОРГАНИЗАЦИЯ'), ('DIS', 'РАЙОН'), ('NUM', 'НОМЕР'), ('HB', 'СПРАВОЧНИК')], max_length=3),
        ),
    ]
