# Generated by Django 4.0.3 on 2022-03-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_values_value_handbook_alter_fields_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='value_handbook',
        ),
    ]
