# Generated by Django 4.0.3 on 2022-03-22 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0008_alter_history_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100, null=True)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.handbook')),
            ],
        ),
        migrations.CreateModel(
            name='HandBookValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_string', models.CharField(default=None, max_length=255, null=True)),
                ('value_int', models.IntegerField(default=None, null=True)),
                ('value_float', models.FloatField(default=None, null=True)),
                ('value_date', models.DateTimeField(default=None, null=True)),
                ('value_file', models.FileField(default=None, null=True, upload_to='')),
                ('value_list', models.CharField(default=None, max_length=100, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task.fields')),
            ],
        ),
        migrations.CreateModel(
            name='HandBookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('dir', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.handbook')),
            ],
        ),
        migrations.CreateModel(
            name='HandBookFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('STR', 'СТРОКА'), ('INT', 'ЦЕЛОЕ ЧИСЛО'), ('FLT', 'ДРОБНОЕ ЧИСЛО'), ('DAT', 'ДАТА'), ('FIL', 'ФАЙЛ'), ('LIS', 'СПИСОК'), ('USR', 'СОТРУДНИК'), ('CMP', 'ОРГАНИЗАЦИЯ'), ('DIS', 'РАЙОН'), ('NUM', 'НОМЕР')], max_length=3)),
                ('title', models.CharField(max_length=25, null=True)),
                ('handbook_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.handbook')),
            ],
        ),
    ]
