# Generated by Django 4.0.3 on 2022-03-22 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_remove_values_value_handbook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handbook', '0002_alter_handbookvalues_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandBookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100, null=True)),
                ('creation_date', models.DateField(auto_now=True)),
                ('creator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HandBookField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('STR', 'СТРОКА'), ('INT', 'ЦЕЛОЕ ЧИСЛО'), ('FLT', 'ДРОБНОЕ ЧИСЛО'), ('DAT', 'ДАТА'), ('FIL', 'ФАЙЛ'), ('LIS', 'СПИСОК'), ('USR', 'СОТРУДНИК'), ('CMP', 'ОРГАНИЗАЦИЯ'), ('DIS', 'РАЙОН'), ('NUM', 'НОМЕР')], max_length=3)),
                ('title', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HandBookObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.handbookcategory')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.handbookobject')),
            ],
        ),
        migrations.RemoveField(
            model_name='handbookfields',
            name='handbook_id',
        ),
        migrations.RemoveField(
            model_name='handbookinfo',
            name='author',
        ),
        migrations.RemoveField(
            model_name='handbookinfo',
            name='dir',
        ),
        migrations.DeleteModel(
            name='HandBook',
        ),
        migrations.DeleteModel(
            name='HandBookInfo',
        ),
        migrations.AddField(
            model_name='handbookcategory',
            name='fields',
            field=models.ManyToManyField(default=None, null=True, to='handbook.handbookfield'),
        ),
        migrations.AddField(
            model_name='handbookvalues',
            name='hb_object',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.handbookobject'),
        ),
        migrations.AlterField(
            model_name='handbookvalues',
            name='field',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.handbookfield'),
        ),
        migrations.DeleteModel(
            name='HandBookFields',
        ),
    ]
