# Generated by Django 4.0.3 on 2022-03-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0003_handbookcategory_handbookfield_handbookobject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbookfield',
            name='category',
            field=models.ManyToManyField(default=None, null=True, to='handbook.handbookcategory'),
        ),
    ]
