# Generated by Django 4.0.3 on 2022-03-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0004_handbookfield_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbookcategory',
            name='fields',
            field=models.ManyToManyField(blank=True, to='handbook.handbookfield'),
        ),
        migrations.AlterField(
            model_name='handbookfield',
            name='category',
            field=models.ManyToManyField(blank=True, to='handbook.handbookcategory'),
        ),
    ]
