# Generated by Django 4.0.3 on 2022-03-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0005_alter_handbookcategory_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handbookfield',
            name='category',
        ),
    ]
